---

- name: Include Steps For ESM Installation
  include: "{{ ellucian_solution_manager_os_tasks }}"
  static: no
  with_first_found:
    - "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
    - "default.yml"
  loop_control:
    loop_var: ellucian_solution_manager_os_tasks
