---

- name: Install Additional Packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - rng-tools
  notify: Restart Tomcat

- name: Enable RNGD
  service:
    name: rngd
    state: started
    enabled: yes
  notify: Restart Tomcat

- name: Deploy Jenkins To Tomcat Server
  copy:
    remote_src: yes
    dest: "{{ tomcat_catalina_home }}/webapps/jenkins.war"
    src: "/usr/lib/jenkins/jenkins.war"
    owner: "{{ esm_user }}"
    group: "{{ esm_group }}"
  notify: Restart Tomcat
